# Generated by Django 2.2.11 on 2020-04-02 11:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='credit',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
